package_assets: always

javascripts:
  default_javascripts:
    - public/javascripts/jquery.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/modernizr.js
    - public/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/screen.css
    - public/stylesheets/custom.css
